### PR TITLE
Add record for the interactive tool type

### PR DESCRIPTION
**Pull request by johnworth**
Adds a new record for interactive tools. Adds a conversion for it as well. 

Tested against the unittest-dedb container image.

### CODE REVIEW

**Review by slr71 — COMMENTED** [review]
The update to `99_versions.sql` is missing. It looks good to me other than that.

**Review by slr71 — APPROVED** [review]
LGTM :shipit:

**Review by yeea — APPROVED** [review]
LGTM, now that I've got the explainer on why INSERT INTO appears twice

**Review by psarando — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
